---
- name: depends
  package: name=nginx state=latest
- name: copy nginx conf
  template: src=nginx.j2 dest=/etc/nginx/nginx.conf
- name: ensure /etc/nginx/conf.d exists
  file: path=/etc/nginx/conf.d state=directory
- name: copy nginx conf for {{project}}
  template: src=project.j2 dest=/etc/nginx/conf.d/{{project}}.conf
- name: nginx enable
  service: name=nginx enabled=yes
- name: nginx restart
  service: name=nginx state=restarted
