---
install_db_packages:
    - postgresql-{{ postgres_version }}
    - postgresql-client-{{ postgres_version }}
    - libpq-dev
    - python-psycopg2
postgresql_conf: /etc/postgresql/{{postgres_version}}/main
postgresql_data: /var/lib/postgresql/{{ postgres_version }}/main
