---
- name: install postgresql
  apt: name={{ item }} state=latest
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2
- name: create db
  become: yes
  become_user: postgres
  postgresql_db: name={{ psql_db_name }}
- name: create user
  become: yes
  become_user: postgres
  postgresql_user: db={{ psql_db_name }} name={{ project_user }} password={{ project_password }} priv=ALL
- name: ensure user does not have unnecessary privilege
  become: yes
  become_user: postgres
  postgresql_user: name={{ project_user }} role_attr_flags=NOSUPERUSER,NOCREATEDB
