---
- name: install postgresql
  apt: name={{ item }} state=latest
  with_items:
    - postgresql-9.4
    - postgresql-client-9.4
    - libpq-dev
    - python-psycopg2
- name: copy postgresql.conf
  template: src=postgresql.j2 dest=/etc/postgresql/{{ postgres_version }}/main/postgresql.conf
- name: copy pg_hba.conf
  template: src=pg_hba.j2 dest=/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf
  register: postgresql_conf
- name: pg restart
  service: name=postgresql state=restarted
  when: postgresql_conf.changed
- name: create db
  become: yes
  become_user: postgres
  postgresql_db: name={{ psql_db_name }}
- name: create user
  become: yes
  become_user: postgres
  postgresql_user: db={{ psql_db_name }} name={{ project_user }} password={{ project_password }} priv=ALL
- name: ensure user does not have unnecessary privilege
  become: yes
  become_user: postgres
  postgresql_user: name={{ project_user }} role_attr_flags=NOSUPERUSER,NOCREATEDB
