---
- name: install packages
  apt: name={{item}} state=present
  with_items:
    - python-pip
    - python-dev
    - git
    - uwsgi
    - uwsgi-plugin-python
    - libjpeg-dev
- name: add project user
  user: name={{project_user}} comment="{{ project }}"
- name: project checkout
  git: repo=https://github.com/torchbox/wagtaildemo.git dest={{project_path}}
  register: repo_update
- name: chown to user
  file: path={{project_path}} owner={{project_user}}
- name: install requirements
  pip: requirements={{project_path}}/requirements.txt
- name: install django-redis-cache
  pip: name=django-redis-cache state=latest
- name: copy local.py
  template: src=local.j2 dest={{ project_path }}/wagtaildemo/settings/local.py
- name: initiate db
  become: yes
  become_user: "{{project_user}}"
  django_manage: command={{item}} app_path={{project_path}}
  with_items:
    - migrate
    - load_initial_data
    - update_index
  when: repo_update.changed
- name: copy uwsgi file
  template: src=uwsgi.j2 dest={{ project_path }}/uwsgi.yaml
- name: get uwsgi PATH
  command: which uwsgi
  register: uwsgi_path
- name: copy service
  template: src=uwsgi.service.j2 dest=/lib/systemd/system/{{project}}.service
  notify:
    - daemon-reload
- name: service enable
  service: name={{project}} enabled=yes
- name: service start
  service: name={{project}} state=started
